# Kibana Configuration
# AIOps-Platform 日志可视化配置
# 版本: 1.0.0

# ===========================================
# 服务器配置
# ===========================================
server.port: 5601
server.host: "0.0.0.0"
server.name: "aiops-kibana"
server.uuid: "550e8400-e29b-41d4-a716-446655440000"

# ===========================================
# Elasticsearch配置
# ===========================================
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.requestTimeout: 30000
elasticsearch.pingTimeout: 3000

# ===========================================
# 路径配置
# ===========================================
path.data: /usr/share/kibana/data

# ===========================================
# 日志配置
# ===========================================
logging:
  appenders:
    default:
      type: console
      layout:
        type: json
  root:
    appenders: [default]
    level: info
  loggers:
    - name: elasticsearch
      level: warn

# ===========================================
# 监控配置
# ===========================================
monitoring.ui.container.elasticsearch.enabled: true