# Ansible Inventory - 主机清单配置
# 定义自愈系统管理的目标主机和服务

all:
  children:
    # ELK Stack 服务器组
    elk_stack:
      children:
        elasticsearch_cluster:
          hosts:
            es-master-01:
              ansible_host: 10.0.1.10
              ansible_user: ansible
              node_role: master
              heap_size: 2g
            es-data-01:
              ansible_host: 10.0.1.11
              ansible_user: ansible
              node_role: data
              heap_size: 4g
            es-data-02:
              ansible_host: 10.0.1.12
              ansible_user: ansible
              node_role: data
              heap_size: 4g
          vars:
            elasticsearch_version: 8.11.0
            cluster_name: aiops-cluster
            network_host: 0.0.0.0
            http_port: 9200
            transport_port: 9300
        
        kibana_servers:
          hosts:
            kibana-01:
              ansible_host: 10.0.1.20
              ansible_user: ansible
          vars:
            kibana_version: 8.11.0
            server_port: 5601
            elasticsearch_hosts:
              - http://10.0.1.10:9200
              - http://10.0.1.11:9200
              - http://10.0.1.12:9200
        
        logstash_servers:
          hosts:
            logstash-01:
              ansible_host: 10.0.1.30
              ansible_user: ansible
            logstash-02:
              ansible_host: 10.0.1.31
              ansible_user: ansible
          vars:
            logstash_version: 8.11.0
            pipeline_workers: 4
            pipeline_batch_size: 125
    
    # 监控系统服务器组
    monitoring_stack:
      children:
        prometheus_servers:
          hosts:
            prometheus-01:
              ansible_host: 10.0.2.10
              ansible_user: ansible
          vars:
            prometheus_version: 2.45.0
            retention_time: 15d
            storage_path: /var/lib/prometheus
        
        grafana_servers:
          hosts:
            grafana-01:
              ansible_host: 10.0.2.20
              ansible_user: ansible
          vars:
            grafana_version: 10.2.0
            admin_user: admin
            admin_password: "{{ vault_grafana_admin_password }}"
        
        alertmanager_servers:
          hosts:
            alertmanager-01:
              ansible_host: 10.0.2.30
              ansible_user: ansible
          vars:
            alertmanager_version: 0.26.0
            cluster_listen_address: 0.0.0.0:9094
    
    # 应用服务器组
    application_servers:
      children:
        web_servers:
          hosts:
            web-01:
              ansible_host: 10.0.3.10
              ansible_user: ansible
              server_role: frontend
            web-02:
              ansible_host: 10.0.3.11
              ansible_user: ansible
              server_role: frontend
          vars:
            nginx_version: 1.24.0
            max_connections: 1024
        
        api_servers:
          hosts:
            api-01:
              ansible_host: 10.0.3.20
              ansible_user: ansible
              server_role: backend
            api-02:
              ansible_host: 10.0.3.21
              ansible_user: ansible
              server_role: backend
          vars:
            java_version: 17
            spring_profiles: production
        
        database_servers:
          hosts:
            db-master:
              ansible_host: 10.0.3.30
              ansible_user: ansible
              db_role: master
            db-slave-01:
              ansible_host: 10.0.3.31
              ansible_user: ansible
              db_role: slave
            db-slave-02:
              ansible_host: 10.0.3.32
              ansible_user: ansible
              db_role: slave
          vars:
            mysql_version: 8.0
            innodb_buffer_pool_size: 2G
    
    # 基础设施服务器组
    infrastructure:
      children:
        load_balancers:
          hosts:
            lb-01:
              ansible_host: 10.0.4.10
              ansible_user: ansible
              lb_role: primary
            lb-02:
              ansible_host: 10.0.4.11
              ansible_user: ansible
              lb_role: backup
          vars:
            haproxy_version: 2.8
            keepalived_enabled: true
        
        cache_servers:
          hosts:
            redis-01:
              ansible_host: 10.0.4.20
              ansible_user: ansible
              redis_role: master
            redis-02:
              ansible_host: 10.0.4.21
              ansible_user: ansible
              redis_role: slave
          vars:
            redis_version: 7.0
            maxmemory: 2gb
            maxmemory_policy: allkeys-lru
        
        message_queues:
          hosts:
            rabbitmq-01:
              ansible_host: 10.0.4.30
              ansible_user: ansible
              rabbitmq_role: primary
            rabbitmq-02:
              ansible_host: 10.0.4.31
              ansible_user: ansible
              rabbitmq_role: secondary
          vars:
            rabbitmq_version: 3.12
            cluster_enabled: true
    
    # Docker容器主机组
    docker_hosts:
      hosts:
        docker-01:
          ansible_host: 10.0.5.10
          ansible_user: ansible
        docker-02:
          ansible_host: 10.0.5.11
          ansible_user: ansible
        docker-03:
          ansible_host: 10.0.5.12
          ansible_user: ansible
      vars:
        docker_version: 24.0.0
        docker_compose_version: 2.21.0
        container_runtime: docker
    
    # Kubernetes集群组
    kubernetes_cluster:
      children:
        k8s_masters:
          hosts:
            k8s-master-01:
              ansible_host: 10.0.6.10
              ansible_user: ansible
            k8s-master-02:
              ansible_host: 10.0.6.11
              ansible_user: ansible
            k8s-master-03:
              ansible_host: 10.0.6.12
              ansible_user: ansible
          vars:
            kubernetes_role: master
            etcd_enabled: true
        
        k8s_workers:
          hosts:
            k8s-worker-01:
              ansible_host: 10.0.6.20
              ansible_user: ansible
            k8s-worker-02:
              ansible_host: 10.0.6.21
              ansible_user: ansible
            k8s-worker-03:
              ansible_host: 10.0.6.22
              ansible_user: ansible
            k8s-worker-04:
              ansible_host: 10.0.6.23
              ansible_user: ansible
          vars:
            kubernetes_role: worker
      vars:
        kubernetes_version: 1.28.0
        pod_network_cidr: 10.244.0.0/16
        service_cidr: 10.96.0.0/12

# 全局变量
vars:
  # SSH配置
  ansible_ssh_private_key_file: ~/.ssh/ansible_rsa
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  
  # Python解释器
  ansible_python_interpreter: /usr/bin/python3
  
  # 超时配置
  ansible_ssh_timeout: 30
  ansible_command_timeout: 300
  
  # 日志配置
  log_level: INFO
  log_path: /var/log/ansible.log
  
  # 安全配置
  become_method: sudo
  become_user: root
  
  # 时区配置
  timezone: Asia/Shanghai
  
  # NTP服务器
  ntp_servers:
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - time.windows.com
  
  # DNS服务器
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4
    - 114.114.114.114
  
  # 监控配置
  monitoring:
    node_exporter_port: 9100
    cadvisor_port: 8080
    blackbox_exporter_port: 9115
  
  # 备份配置
  backup:
    enabled: true
    retention_days: 7
    backup_path: /backup
    s3_bucket: aiops-backups
  
  # 安全更新
  security_updates:
    enabled: true
    auto_reboot: false
    reboot_time: "02:00"